FROM --platform=linux/amd64 ubuntu:20.04

ENV JAVA_HOME=/usr/lib/jvm/default-java

# Change apt repository to a China network friendly site.
# RUN sed -i s@/archive.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list
# RUN sed -i s@/security.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list

RUN apt-get clean
RUN apt-get update

RUN apt-get install -y --no-install-recommends
RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common
RUN apt-get install -y lsb-release
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y libssl-dev
RUN apt-get install -y libcrypto++-dev
RUN apt-get install -y libc++-dev

# Install java
RUN apt-get -y install default-jdk

# Install maven
RUN apt-get -y install maven

# Maven aliyun
COPY mvn_settings.xml /root/.m2/settings.xml

# Copy dynamic library
COPY src/main/resources/lib/*.so /usr/lib/
