source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'CallAPI_Example' do
  pod 'CallAPI', :path => '../'
  pod 'YYCategories'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
